name: Manual Work Flow
description: |
  手動実行で指定された文字列を加工して返します
inputs:
  message:
    default: "World!!"
    required: false
    description: 指定の文字を加工して返します。
outputs:
  hello-message:
    value: ${{ steps.hello.outputs.hello }}
    description: 加工した文字列
runs:
  using: composite
  steps:
    - id: hello
      run: echo "hello=Hello, $MESSAGE" >> "${GITHUB_OUTPUT}"
      shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
    - run: echo {{ steps.hello.outputs.hello }}
      shell: bash
