name: Function demo

on: workflow_dispatch

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      ########################################################
      ##                     json                           ##
      ########################################################

      - name: Output Json
        id: json
        run: echo "json=[{\"name\":\"user1\"},{\"name\":\"user2\"}]" >> "${GITHUB_OUTPUT}"

      - name: Json Function
        run: |
          echo "${NAMES}"
        env:
          NAMES: ${{ toJson(fromJson(steps.json.outputs.json).*.name) }}

      ########################################################
      ##                     json                           ##
      ########################################################
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: "contains('Hello', 'llo')=${{ contains('Hello', 'llo') }}"
      - run: echo "${{ contains('Hello', 'He') }}"
